In [38]:
import numpy as np
import pandas as pd

In [19]:
input_dim = 5
nodes = 3

In [20]:
params = {"weights" : (input_dim*nodes), "bias" : nodes}

In [21]:
params

{'weights': 15, 'bias': 3}

In [22]:
np.ones((nodes,input_dim))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.zeros((nodes,1))

array([[0.],
       [0.],
       [0.]])

In [28]:
nodes = [2]
layers = 1

In [29]:
curr = 4
layers = 2
nodes.append(curr)

In [30]:
nodes

[2, 4]

In [31]:
nodes[layers-2]

2

In [36]:
params = {}

In [37]:
params["w1"] = [1,1]

In [41]:
df = pd.DataFrame({"col1" : [1,2,3], "col2" : [4,5,6]})
df

col1  col2
0     1     4
1     2     5
2     3     6

In [43]:
np.array(df)[0]

array([1, 4], dtype=int64)

In [44]:
np.array(np.array([[1,4],[2,5],[3,6]]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
wts = np.array([[1,2],[4,5]])
b = np.array([[5]])
x = np.array([[2,3]])

In [55]:
x.shape

(1, 2)

In [56]:
(2*1)+(3*2)+5

13

In [58]:
np.dot(wts,x.T) + b

array([[13],
       [28]])